// web/src/pages/Builds.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'
import { Table } from 'patternfly-react'

import { fetchBuilds } from '../api'
import TableFilters from '../containers/TableFilters'


class BuildsPage extends TableFilters {
  static propTypes = {
    tenant: PropTypes.object
  }

  constructor () {
    super()

    this.prepareTableHeaders()
    this.state = {
      builds: null,
      currentFilterType: this.filterTypes[0],
      activeFilters: [],
      currentValue: ''
    }
  }

  updateData = (filters) => {
    let queryString = ''
    if (filters) {
      filters.forEach(item => queryString += '&' + item.key + '=' + item.value)
    }
    this.setState({builds: null})
    fetchBuilds(this.props.tenant.apiPrefix, queryString).then(response => {
      this.setState({builds: response.data})
    })
  }

  componentDidMount () {
    document.title = 'Zuul Build'
    if (this.props.tenant.name) {
      this.updateData(this.getFilterFromUrl())
    }
  }

  componentDidUpdate (prevProps) {
    if (this.props.tenant.name !== prevProps.tenant.name) {
      this.updateData(this.getFilterFromUrl())
    }
  }

  prepareTableHeaders() {
    const headerFormat = value => <Table.Heading>{value}</Table.Heading>
    const cellFormat = (value) => (
      <Table.Cell>{value}</Table.Cell>)
    const linkCellFormat = (value) => (
      <Table.Cell>
        <a href={value} target='_blank' rel='noopener noreferrer'>link</a>
      </Table.Cell>
    )
    const linkBuildFormat = (value) => (
      <Table.Cell>
        <Link to={this.props.tenant.linkPrefix + '/build/' + value}>link</Link>
      </Table.Cell>
    )
    this.columns = []
    this.filterTypes = []
    const myColumns = [
      'build',
      'job',
      'project',
      'branch',
      'pipeline',
      'change',
      'duration',
      'log',
      'start time',
      'result']
    myColumns.forEach(column => {
      let prop = column
      let formatter = cellFormat
      // Adapt column name and property name
      if (column === 'build') {
        prop = 'uuid'
        formatter = linkBuildFormat
      }
      if (column === 'job') {
        prop = 'job_name'
      } else if (column === 'start time') {
        prop = 'start_time'
      } else if (column === 'change') {
        prop = 'ref_url'
        formatter = linkCellFormat
      } else if (column === 'log') {
        prop = 'log_url'
        formatter = linkCellFormat
      }
      const label = column.charAt(0).toUpperCase() + column.slice(1)
      this.columns.push({
        header: {label: label, formatters: [headerFormat]},
        property: prop,
        cell: {formatters: [formatter]}
      })
      if (prop !== 'start_time' && prop !== 'ref_url' && prop !== 'duration'
          && prop !== 'log_url' && prop !== 'uuid') {
        this.filterTypes.push({
          id: prop,
          title: label,
          placeholder: 'Filter by ' + label,
          filterType: 'text',
        })
      }
    })
    // Add build filter at the end
    this.filterTypes.push({
      id: 'uuid',
      title: 'Build',
      palceholder: 'Filter by Build UUID',
      fileterType: 'text',
    })
  }

  renderTable (builds) {
    return (
      <Table.PfProvider
        striped
        bordered
        columns={this.columns}
      >
        <Table.Header/>
        <Table.Body
          rows={builds}
          rowKey='uuid'
          onRow={(row) => {
            switch (row.result) {
              case 'SUCCESS':
                return { className: 'success' }
              default:
                return { className: 'warning' }
            }
          }} />
      </Table.PfProvider>)
  }

  render() {
    const { builds } = this.state
    return (
      <React.Fragment>
        {this.renderFilter()}
        {builds ? this.renderTable(builds) : <p>Loading...</p>}
      </React.Fragment>
    )
  }
}

export default connect(state => ({tenant: state.tenant}))(BuildsPage)

// web/builds/builds.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { HttpClient, HttpParams } from '@angular/common/http'
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/map'

import ZuulService from '../zuul/zuul.service'
import Build from './build'


@Component({
  template: require('./builds.component.html')
})
export default class BuildsComponent implements OnInit {
  builds: Build[]
  pipeline: string
  job_name: string
  project: string
  tenant: string

  constructor(
    private http: HttpClient, private route: ActivatedRoute,
    private zuul: ZuulService
  ) {}

  ngOnInit() {

    this.tenant = this.route.snapshot.paramMap.get('tenant')

    this.pipeline = this.route.snapshot.queryParamMap.get('pipeline')
    this.job_name = this.route.snapshot.queryParamMap.get('job_name')
    this.project = this.route.snapshot.queryParamMap.get('project')

    this.buildsFetch()
  }

  buildsFetch(): void  {
    let params = new HttpParams()
    if (this.pipeline) { params = params.set('pipeline', this.pipeline) }
    if (this.job_name) { params = params.set('job_name', this.job_name) }
    if (this.project) { params = params.set('project', this.project) }

    const remoteLocation = this.zuul.getSourceUrl('builds', this.tenant)
    this.http.get<Build[]>(remoteLocation, {params: params})
      .subscribe(builds => {
        for (const build of builds) {
          /* Fix incorect url for post_failure job */
          /* TODO(mordred) Maybe let's fix this server side? */
          if (build.log_url === build.job_name) {
            build.log_url = undefined
          }
        }
        this.builds = builds
      })
  }

  getRowClass(build: Build): string {
    if (build.result === 'SUCCESS') {
      return 'success'
    } else {
      return 'warning'
    }
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <span style="float: right; margin-top: 7px;">
    <form class="form-inline" #buildsForm="ngForm">
      <div class="form-group">
        <label for="pipeline">Pipeline:</label>
        <input class="form-control" id="pipeline"
               [(ngModel)]="pipeline" name="pipeline" />
      </div>
      <div class="form-group">
        <label for="job_name">Job:</label>
        <input class="form-control" id="job_name"
               [(ngModel)]="job_name" name="job_name" />
      </div>
      <div class="form-group">
        <label for="project">Project:</label>
        <input class="form-control" id="project"
               [(ngModel)]="project" name="project">
      </div>
      <button type="submit" class="btn" (click)='buildsFetch()'>
          Refresh
      </button>
    </form>
  </span>
</div>
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Job</th>
      <th>Project</th>
      <th>Branch</th>
      <th>Pipeline</th>
      <th>Change</th>
      <th>Duration</th>
      <th>Log url</th>
      <th>Start time</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let build of builds" [class]="getRowClass(build)">
      <td>{{ build.job_name }}</td>
      <td>{{ build.project }}</td>
      <td>{{ build.branch }}</td>
      <td>{{ build.pipeline }}</td>
      <td><a href="{{ build.ref_url }}" target="_self">change</a></td>
      <td>{{ build.duration }} seconds</td>
      <td><a *ngIf="build.log_url" href="{{ build.log_url }}" target="_self">logs</a></td>
      <td>{{ build.start_time }}</td>
      <td>{{ build.result }}</td>
    </tr>
  </tbody>
</table>
