// web/src/containers/jobs/Jobs.jsx
// Copyright 2018 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import * as React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'
import { Table } from 'patternfly-react'


class JobsList extends React.Component {
  static propTypes = {
    tenant: PropTypes.object,
    jobs: PropTypes.array,
  }

  render () {
    const { jobs } = this.props

    const headerFormat = value => <Table.Heading>{value}</Table.Heading>
    const cellFormat = (value) => (
      <Table.Cell>{value}</Table.Cell>)
    const cellJobFormat = (value) => (
      <Table.Cell>
        <Link to={this.props.tenant.linkPrefix + '/job/' + value}>
          {value}
        </Link>
      </Table.Cell>)
    const cellBuildFormat = (value) => (
      <Table.Cell>
        <Link to={this.props.tenant.linkPrefix + '/builds?job_name=' + value}>
          builds
        </Link>
      </Table.Cell>)
    const columns = []
    const myColumns = ['name', 'description', 'Last builds']
    myColumns.forEach(column => {
      let formatter = cellFormat
      let prop = column
      if (column === 'name') {
        formatter = cellJobFormat
      }
      if (column === 'Last builds') {
        prop = 'name'
        formatter = cellBuildFormat
      }
      columns.push({
        header: {label: column,
          formatters: [headerFormat]},
        property: prop,
        cell: {formatters: [formatter]}
      })
    })
    return (
      <Table.PfProvider
        striped
        bordered
        hover
        columns={columns}
        >
        <Table.Header/>
        <Table.Body
          rows={jobs}
          rowKey="name"
          />
      </Table.PfProvider>
    )
  }
}

export default connect(state => ({
  tenant: state.tenant,
}))(JobsList)

// web/jobs/jobs.component.ts
// Copyright 2017 Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License. You may obtain
// a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import { Component, OnInit } from '@angular/core'
import { HttpClient } from '@angular/common/http'
import { ActivatedRoute } from '@angular/router'

import ZuulService from '../zuul/zuul.service'
import JobDetails from './details'
import Job from './job'

@Component({
  template: require('./jobs.component.html')
})
export default class JobsComponent implements OnInit {

  jobs: Job[]
  tenant?: string

  constructor(
    private http: HttpClient, private route: ActivatedRoute,
    private zuul: ZuulService
  ) {}

  ngOnInit() {
    this.tenant = this.route.snapshot.paramMap.get('tenant')
    this.jobsFetch()
  }

  jobsFetch(): void {
    this.http.get<Job[]>(this.zuul.getSourceUrl('jobs', this.tenant))
      .subscribe(jobs => this.injestJobs(jobs))
  }

  injestJobs(jobs: Job[]): void {
    for (const job of jobs) {
      job.expanded = false
    }
    this.jobs = jobs
  }
}

<!--
Copyright 2017 Red Hat

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->
<div class="container-fluid">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Last builds</th>
      </tr>
    </thead>
    <tbody>
      <ng-container *ngFor="let job of jobs">
        <tr>
          <td>{{ job.name }}</td>
          <td>{{ job.description }}</td>
          <td><a [routerLink]="['../builds.html']"
                 [queryParams]="{job_name: job.name}" target="_self">
              builds</a></td>
        </tr>
        <tr *ngIf="job.expanded">
          <td colspan="3">
            <ul class="list-group">
              <li class="list-group-item" *ngFor="let detail of job.details">
                <!-- TODO: make clickable link to cgit files ? -->
                {{ detail.source_context }}
              </li>
            </ul>
          </td>
        </tr>
      </ng-container>
    </tbody>
  </table>
</div>
